apiVersion: apps/v1
kind: Deployment
metadata:
  name: igait-stage1-media-conversion
  namespace: igait
  labels:
    app: igait-stage1-media-conversion
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: igait-stage1-media-conversion
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: igait-stage1-media-conversion
    spec:
      containers:
      - image: ghcr.io/igait-niu/igait/igait-stage1-media-conversion:sha-f4437cd
        name: igait-stage1-media-conversion
        env:
        - name: AWS_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_S3_BUCKET
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: FIREBASE_RTDB_URL
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: FIREBASE_RTDB_URL
        - name: FIREBASE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: FIREBASE_ACCESS_KEY
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
            ephemeral-storage: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
            ephemeral-storage: 256Mi