apiVersion: apps/v1
kind: Deployment
metadata:
  name: igait-stage2-validity-check
  namespace: igait
  labels:
    app: igait-stage2-validity-check
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: igait-stage2-validity-check
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: igait-stage2-validity-check
    spec:
      containers:
      - image: ghcr.io/igait-niu/igait/igait-stage2-validity-check:sha-9d4fe67
        name: igait-stage2-validity-check
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 32Mi
          requests:
            cpu: 100m
            memory: 128Mi