apiVersion: apps/v1
kind: Deployment
metadata:
  name: igait-stage4-pose-estimation
  namespace: igait
  labels:
    app: igait-stage4-pose-estimation
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: igait-stage4-pose-estimation
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: igait-stage4-pose-estimation
    spec:
      containers:
      - image: ghcr.io/igait-niu/igait/igait-stage4-pose-estimation:sha-f1b435d
        name: igait-stage4-pose-estimation
        env:
        - name: AWS_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_S3_BUCKET
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: FIREBASE_RTDB_URL
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: FIREBASE_RTDB_URL
        - name: FIREBASE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: FIREBASE_ACCESS_KEY
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 32Mi
          requests:
            cpu: 100m
            memory: 128Mi
