apiVersion: apps/v1
kind: Deployment
metadata:
  name: igait-backend
  namespace: igait
  labels:
    app: igait-backend
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: igait-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: igait-backend
    spec:
      containers:
      - image: ghcr.io/igait-niu/igait/igait-backend:sha-f4e145a
        name: igait-backend
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: PORT
        - name: RUST_LOG
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: RUST_LOG
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: GOOGLE_APPLICATION_CREDENTIALS
        - name: FIREBASE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: FIREBASE_ACCESS_KEY
        - name: FIREBASE_RTDB_URL
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: FIREBASE_RTDB_URL
        - name: AWS_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_S3_BUCKET
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: OPENAI_API_KEY
        - name: OPENAI_ASSISTANT_ID
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: OPENAI_ASSISTANT_ID
        - name: OPENAI_VECTOR_STORE_ID
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: OPENAI_VECTOR_STORE_ID
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
            ephemeral-storage: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
            ephemeral-storage: 64Mi
        volumeMounts:
        - name: gcp-key
          mountPath: /credentials
          readOnly: true
      volumes:
      - name: gcp-key
        secret:
          secretName: gcp-key