apiVersion: v1
kind: Service
metadata:
  name: igait-backend
  namespace: igait
  labels:
    app: igait-backend
spec:
  type: LoadBalancer
  selector:
    app: igait-backend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP