apiVersion: apps/v1
kind: Deployment
metadata:
  name: igait-stage2-validity-check
  namespace: igait
  labels:
    app: igait-stage2-validity-check
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: igait-stage2-validity-check
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: igait-stage2-validity-check
    spec:
      containers:
      - image: ghcr.io/igait-niu/igait/igait-stage2-validity-check:sha-52d27b7
        name: igait-stage2-validity-check
        env:
        - name: AWS_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_S3_BUCKET
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: FIREBASE_RTDB_URL
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: FIREBASE_RTDB_URL
        - name: FIREBASE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: FIREBASE_ACCESS_KEY
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
            ephemeral-storage: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
            ephemeral-storage: 512Mi