apiVersion: apps/v1
kind: Deployment
metadata:
  name: igait-stage7-finalize
  namespace: igait
  labels:
    app: igait-stage7-finalize
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: igait-stage7-finalize
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: igait-stage7-finalize
    spec:
      containers:
      - image: ghcr.io/igait-niu/igait/igait-stage7-finalize:sha-f4e145a
        name: igait-stage7-finalize
        env:
        - name: AWS_S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_S3_BUCKET
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: FIREBASE_RTDB_URL
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: FIREBASE_RTDB_URL
        - name: FIREBASE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: igait-secrets
              key: FIREBASE_ACCESS_KEY
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
            ephemeral-storage: 64Mi
          requests:
            cpu: 50m
            memory: 64Mi
            ephemeral-storage: 32Mi
