apiVersion: apps/v1
kind: Deployment
metadata:
  name: igait-frontend
  namespace: igait
  labels:
    app: igait-frontend
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: igait-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: igait-frontend
    spec:
      containers:
      - image: ghcr.io/igait-niu/igait/igait-frontend:sha-1c753eb
        name: igait-frontend
        ports:
        - containerPort: 4173
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
            ephemeral-storage: 128Mi
          requests:
            cpu: 100m
            memory: 512Mi
            ephemeral-storage: 32Mi
        readinessProbe:
          httpGet:
            path: /
            port: 4173
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 4173
          initialDelaySeconds: 10
          periodSeconds: 30
