apiVersion: v1
kind: Service
metadata:
  name: igait-frontend
  namespace: igait
  labels:
    app: igait-frontend
spec:
  type: LoadBalancer
  selector:
    app: igait-frontend
  ports:
  - port: 80
    targetPort: 4173
    protocol: TCP